회원가입 라우터 구현
busoMarcat/v1_server pull request #13
Opened 2023-08-03 15:05 UTC by jyj1289

회원가입 라우터 구현했습니다

2023-08-04 12:26 UTC, qlido requested changes

2023-08-04 12:26 UTC, qlido commented on src/routes/memberRouter.js
> +require("dotenv").config();
import 정리하시고 dotenv는 첫줄에 있어야 합니다

2023-08-04 12:26 UTC, qlido commented on src/routes/memberRouter.js
> +const saltRounds = parseInt(env.ROUNDS);
env변수가 의미가 없는거 같습니다. 구조분해할당 검색하시고 수정하시면 좋을 것 같습니다. ROUND가 없으면 고장날 수도 있겠네요

2023-08-04 12:26 UTC, qlido commented on src/routes/memberRouter.js
> +router.use(express.json());
이코드는 app.js에서 적혀있어 의미없는 로직입니다

2023-08-04 12:26 UTC, qlido commented on src/routes/memberRouter.js
> +  }
이런 방식은 보안상 문제가 있어 통합해서 확인하는 것이 좋습니다
https://www.boannews.com/media/view.asp?idx=41423

2023-08-04 12:26 UTC, qlido commented on src/routes/memberRouter.js
> +    });
아이디 존재 여부를 확인하는 로직이 필요하지 않을까요?

2023-08-04 12:26 UTC, qlido commented on src/routes/memberRouter.js
> +    res.status(500).json({ success: false });
위에있는 에러와 형태 통일이 필요한거 같아요

2023-08-05 10:36 UTC, qlido commented on src/routes/memberRouter.js
> +    return;
```suggestion
    return res.status(400).json({ error: "아이디 혹은 비밀번호 혹은 닉네임이 입력되지 않았습니다" });
    
```

2023-08-31 03:09 UTC, HUN1i approved these changes

2023-08-31 03:09 UTC, merged